# Generated by Django 5.2.8 on 2025-12-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendar_system', '0001_initial'),
        ('maintenance', '0004_maintenancerequest_requester_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='accounts.staffprofile')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='maintenance.maintenancerequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
