# Generated by Django 5.2.8 on 2025-11-29 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_role', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('issue_photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='completed_photos/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
