# Generated by Django 5.2.8 on 2025-11-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='requester_name',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('staff', 'Staff')], default='Admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.floor'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requester_role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('staff', 'Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.room'),
        ),
    ]
