# Generated by Django 5.2.8 on 2025-11-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenancerequest_requester_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='requester_role',
        ),
    ]
