# Generated by Django 5.2.8 on 2025-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenancerequest_requester_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='requester_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
