# Generated by Django 5.2.8 on 2025-12-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building', 'number'], 'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor__number', 'name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('office', 'Office'), ('restroom', 'Restroom'), ('storage', 'Storage'), ('utility', 'Utility'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='has_floors',
            field=models.BooleanField(default=True, help_text='Whether this building has multiple floors (e.g., Annex/NB) or is ground-level only (e.g., DFA/Grounds)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.PositiveIntegerField(default=0, help_text='Total number of floors in this building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(help_text='The building this floor belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='label',
            field=models.CharField(help_text="Human-readable label (e.g., 'Ground Floor', '2nd Floor', 'Rooftop')", max_length=50),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.PositiveIntegerField(help_text='Floor number (e.g., 1, 2, 3, 4)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(help_text='The building this room is located in', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='The floor this room is on (optional for ground-level buildings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text="Room identifier (e.g., 'Room A4', 'Laboratory 1', 'Office 203')", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'floor', 'name')},
        ),
    ]
